### ISSUE TITLE
PDF export via chrome doesn't respect map

### ISSUE THREAD

**Issue by DaveParr** [satRdays/sponsoring#6]
Thanks for the prior work folks, this is a real time saver. I pinned it up at the top of the org, hope thats ok :)

When exporting the knited slides [according to the xarigan suggested method](https://github.com/yihui/xaringan/wiki/Export-Slides-to-PDF#manual-conversion-via-web-browser) the map doesn't get rendered correctly, and looks like it [impacts the background on that slide](https://github.com/satRdays/cardiff2019sponsors/blob/1b5847b0a6f7fcec7420fea0e2786be8cea791a3/satRday-sponsors.pdf)

Is there a different/preferred method to convert to pdf/self-contained/emailable file?

**Comment by beatrizmilz** [comment]
Hello! Have you tried the function chrome_print() from the package pagedown? 

I tested here and this is the result I got:

`pagedown::chrome_print("presentation-en.html")`



![chromeprint](https://user-images.githubusercontent.com/42153618/66054927-1d456980-e50b-11e9-9395-0298dd1ff9ed.PNG)

**Comment by DaveParr** [comment]
I hadn't. I was using the manual method. If this is the expected method and works as expected, then there's no issue :)

**Comment by beatrizmilz** [comment]
This method is explained in the [documentation of the package xaringan](https://github.com/yihui/xaringan/wiki/Export-Slides-to-PDF#with-the-pagedown-package-and-chrome).



Do you think is worth to add this information to the README file? In the [section "how to"](https://github.com/satRdays/sponsoring#how-to).

**Comment by beatrizmilz** [comment]
Yesterday someone asked me how to export these slides in PDF (which is related to this question). @ColinFay  do you think is worth to add this information (about how to export the slides in PDF with `pagedown::chrome_print("presentation-en.html")` ) in the [section "how to"](https://github.com/satRdays/sponsoring#how-to)? I can make a PR but I want to know if is ok to do it.
